config/routes.rb
Rails.application.routes.draw do

  resources :directors
  resources :actors
  resources :movies do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_and_belongs_to_many :movies

  def to_s
    self.name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_and_belongs_to_many :movies

  def to_s
    self.name
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_and_belongs_to_many :actors
  has_and_belongs_to_many :directors

  def self.search(query)
    self.where('title LIKE ?', "%#{query}%").order('id DESC')
  end

  def to_s
    self.title
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @movies = Movie.search(params[:query])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :runtime, :genre, :plot, :language, :country, :awards, :poster_url, :imdb_id, :imdb_rating, :director_ids => [], :actor_ids => [])
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @movies = Movie.all.sample(10)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def render_imdb_rating(rating)

    rating = rating.to_f
    bg = if rating < 2.0
              "bg-danger"
            elsif rating > 2.0 and rating < 4.0
              "bg-warning"
            elsif rating >= 4.0 and rating < 6.0
              "bg-info"
            elsif rating >= 6.0 and rating < 8.0
              "bg-success"
            elsif rating >= 8.0
              ""
            end

    "<div class=\"progress\">
      <div class=\"progress-bar progress-bar-striped #{bg}\" role=\"progressbar\"
        style=\"width: #{rating*10.0}%\" aria-valuenow=\"#{rating*10.0}\"
        aria-valuemin=\"0\" aria-valuemax=\"100\">#{rating}</div>
    </div>".html_safe
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/actors/_form.html.erb
<%= simple_form_for(@actor, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<div class="container">
  <h1>Editing Actor</h1>

  <%= render 'form', actor: @actor %>

  <%= link_to 'Show', @actor, class: "btn btn-primary" %>
  <%= link_to 'Back', actors_path, class: "btn btn-secondary" %>
</div>

app/views/actors/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Actors</h1>

  <%= link_to 'New Actor', new_actor_path, class: "btn btn-primary" %>
  <br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Some movies</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @actors.each do |actor| %>
        <tr>
          <td><%= actor.name %></td>
          <td><%= actor.movies.sample(3).join ", " %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, actor, class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_actor_path(actor), class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, actor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/actors/new.html.erb
<div class="container">
  <h1>New Actor</h1>

  <%= render 'form', actor: @actor %>

  <%= link_to 'Back', actors_path, class: "btn btn-secondary" %>
</div>

app/views/actors/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h2><%= @actor %>'s movies</h2>

  <%= render partial: "movies/movies", locals: {movies: @actor.movies} %>

  <%= link_to 'Edit', edit_actor_path(@actor), class: "btn btn-primary" %>
  <%= link_to 'Back', actors_path, class: "btn btn-secondary" %>
</div>

app/views/directors/_form.html.erb
<%= simple_form_for(@director, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<div class="container">
  <h1>Editing Director</h1>

  <%= render 'form', director: @director %>

  <%= link_to 'Show', @director, class: "btn btn-primary" %>
  <%= link_to 'Back', directors_path, class: "btn btn-secondary" %>
</div>

app/views/directors/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Directors</h1>

  <%= link_to 'New director', new_director_path, class: "btn btn-primary" %>
  <br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Some movies</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @directors.each do |director| %>
        <tr>
          <td><%= director.name %></td>
          <td><%= director.movies.sample(3).join ", " %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, director, class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_director_path(director), class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, director, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/directors/new.html.erb
<div class="container">
  <h1>New Director</h1>

  <%= render 'form', director: @director %>

  <%= link_to 'Back', directors_path, class: "btn btn-secondary" %>
</div>

app/views/directors/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h2><%= @director %>'s movies</h2>

  <%= render partial: "movies/movies", locals: {movies: @director.movies} %>

  <%= link_to 'Edit', edit_director_path(@director), class: "btn btn-primary" %>
  <%= link_to 'Back', directors_path, class: "btn btn-secondary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/cbcb5949ff.js"></script>
  </head>

  <body>
    <div class="collapse bg-inverse" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 py-4">
            <h4 class="text-white">Sobre a Movie Store</h4>
            <p class="text-muted">Nós insistimos em vender filmes.</p>
          </div>
          <div class="col-sm-4 py-4">
            <h4 class="text-white">Opções</h4>
            <ul class="list-unstyled">
              <li><%= link_to "Movies", movies_path %></li>
              <li><%= link_to "Actors", actors_path %></li>
              <li><%= link_to "Directors", directors_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-inverse bg-inverse">
      <div class="container d-flex justify-content-between">
        <%= link_to "Movie Store", root_path, class: "navbar-brand" %>
        <%= form_tag(search_movies_path, method: :get) do %>
          <%= text_field_tag :query, params[:query], placeholder: "Busque por títulos", class: "form-control" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>

      <%= yield %>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Movie Store é uma aplicação exemplo utilizada durante o <a href="http://cursorails.kutzke.com.br">curso de Ruby on Rails</a></p>
      </div>
    </footer>
  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for(movie, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>

    <%= f.input :year %>

    <%= f.input :runtime %>

    <%= f.input :genre %>

    <%= f.input :plot %>

    <%= f.input :language %>

    <%= f.input :country %>

    <%= f.input :awards %>

    <%= f.input :poster_url %>

    <%= f.input :imdb_id %>

    <%= f.input :imdb_rating %>

    <%= f.association :directors, collection: Director.all, input_html: { multiple: "multiple", class: "multiselect"} %>

    <%= f.association :actors, collection: Actor.all, input_html: { multiple: "multiple", class: "multiselect"} %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="card">
  <img class="card-img-top" src="<%= movie.poster_url %>" width="100%" alt="<%= movie.title %>">
  <div class="card-block">
    <h4 class="card-title">
      <%= movie.title %>
    </h4>
    <h6><small>IMDB Rating: <%= render_imdb_rating movie.imdb_rating %></small></h6>
    <dl class="card-text">
      <dt><%= "Director".pluralize(movie.directors.count) %></dt>
      <dd>
        <% movie.directors.each do |director| %>
          <%= link_to director, director %>
          <%= ", ".html_safe unless director == movie.directors.last %>
        <% end %>
      </dd>
      <dt>Actors</dt>
      <dd>
        <% movie.actors.each do |actor| %>
          <%= link_to actor, actor %>
          <%= ", ".html_safe unless actor == movie.actors.last %>
        <% end %>
      </dd>
      <dt>Plot</dt><dd class="text-justify"><small><%= truncate(movie.plot, length: 200) %></small></dd>
    </dl>
  </div>
  <div class="card-footer">
    <div class="text-center">
      <%= link_to 'More', movie_path(movie), class: "btn btn-primary bt-small" %>
    </div>
  </div>
</div>

app/views/movies/_movies.html.erb
<div class="row">
  <div class="card-columns">
    <%= render movies %>
  </div>
</div>

app/views/movies/edit.html.erb
<div class="container">

  <h1>Editing Movie</h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Show', @movie, class: "btn btn-primary" %>
  <%= link_to 'Back', movies_path, class: "btn btn-secondary" %>

</div>

app/views/movies/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Movies</h1>
  <%= link_to 'New Movie', new_movie_path, class: "btn btn-primary" %>
  <br>
  
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th></th>
        <th>#</th>
        <th>Title</th>
        <th>Plot</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= image_tag movie.poster_url, height: "100px" %></td>
          <td><%= movie.id %></td>
          <td><%= movie.title %></td>
          <td><small><%= truncate(movie.plot, length: 200) %></small></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, movie, class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_movie_path(movie), class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/movies/new.html.erb
<div class="container">

  <h1>New Movie</h1>

  <%= render 'form', movie: @movie %>

  <%= link_to 'Back', movies_path, class: "btn btn-secondary" %>

</div>

app/views/movies/search.html.erb
<div class="container">
  <h4>Você procurou por: "<%= params[:query] %>"</h4>

  <%= render partial: "movies/movies", locals: {movies: @movies} %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <% unless notice.nil? %>
    <p id="notice"><%= notice %></p>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <figure class="figure">
        <img src="<%= @movie.poster_url %>" class="figure-img img-fluid rounded" alt="<%= @movie.title  %>">
      </figure>
    </div>
    <div class="col-md-9">

      <dl>
        <dt>Title</dt>
        <dd><%= @movie.title %></dd>

        <dt>Year</dt>
        <dd><%= @movie.year %></dd>

        <dt>Runtime</dt>
        <dd><%= @movie.runtime %></dd>

        <dt>Genre</dt>
        <dd><%= @movie.genre %></dd>

        <dt><%= "Director".pluralize(@movie.directors.count)%></dt>
        <dd>
          <% @movie.directors.each do |director| %>
            <%= link_to director, director %>
            <%= ", ".html_safe unless director == @movie.directors.last %>
          <% end %>
        </dd>

        <dt><%= "Actor".pluralize(@movie.actors.count)%></dt>
        <dd>
          <% @movie.actors.each do |actor| %>
            <%= link_to actor, actor %>
            <%= ", ".html_safe unless actor == @movie.actors.last %>
          <% end %>
        </dd>

        <dt>Plot</dt>
        <dd><%= @movie.plot %></dd>

        <dt>Language</dt>
        <dd><%= @movie.language %></dd>

        <dt>Country</dt>
        <dd><%= @movie.country %></dd>

        <dt>Awards</dt>
        <dd><%= @movie.awards %></dd>

        <dt>Imdb</dt>
        <dd><%= @movie.imdb_id %></dd>

        <dt>Imdb rating</dt>
        <dd>
          <%= render_imdb_rating @movie.imdb_rating %>
        </dd>
      </dl>

        <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-primary" %>
        <%= link_to 'Back', movies_path, class: "btn btn-secondary" %>
    </div>
  </div>


</div>

app/views/store/index.html.erb
<% unless notice.nil? %>
  <div id="notice" class="alert alert-info"><%= notice %></div>
<% end %>


<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Compre os melhores filmes!</h1>
    <p class="lead text-muted">Porque sua internet será limitada um dia!</p>
    <p>
      <a href="#" class="btn btn-primary">Faça seu acadastro</a>
      <a href="#" class="btn btn-secondary">Já sou usuário</a>
    </p>
  </div>
</section>


<div class="container">
  <h2>Alguns dos nossos melhores filmes ...</h2>

  <%= render partial: "movies/movies", locals: {movies: @movies} %>
</div>